[package]
name = "typst-languagetool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde.workspace = true
substring.workspace = true
typst-syntax.workspace = true
j4rs.workspace = true
clap.workspace = true

[build-dependencies]
j4rs.workspace = true
tempfile.workspace = true


[workspace]
members = [".", "cli", "lsp"]

[workspace.dependencies]
typst-languagetool = { path = "." }
annotate-snippets = "0.11.0"
clap = { version = "4.3.21", features = ["derive"] }
notify = "6.0.1"
notify-debouncer-mini = "0.3.0"
serde = "1.0.183"
serde_json = "1.0.104"
substring = "1.4.5"
typst-syntax = { git = "https://github.com/typst/typst.git", tag = "v0.11.0" }
lsp-server = "0.7.6"
lsp-types = "0.95.0"
pollster = "0.3.0"
j4rs = "0.18.0"
tempfile = "3.10.1"
